name: Docker Image Release

on:
  push:
    branches: ["dev", "main"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TARGET_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v2

      - name: Sets env vars for release
        run: |
          echo "TARGET_TAG=latest" >> $GITHUB_ENV
        if: github.ref_name == 'main'

      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          tags: ${{ env.TARGET_TAG }}
          images: docker.io/infinytum/ingress

      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/s390x,linux/ppc64le
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
